### ISSUE TITLE
proxy checker doesnt work good

### ISSUE THREAD

**Issue by djoey123** [yanikore/phpBrute#3] opened 2017-10-26 11:05 UTC
Proxy checker give a lot of false working proxys. gived 100 to an other checker 100 didnt working, gived same amount gives 88 working on proxy checker...
if I add --proxy-type=l1,l2
i dont get any working proxy`s

**Comment by yani** [comment] 2017-10-26 17:44
I think that your other checker doesn't allow Transparent proxies. You should try a few manually and load the judge url. The default judge url is: http://proxyjudge.us/azenv.php

**Comment by djoey123** [comment] 2017-10-27 10:31
Inserted 32925 proxies.
Checked working proxys phpbrute: 32238
Checked 32238 of phpbrute with an other checker(not an php checker)
working proxys: 2313

all proxys what i checked now are not transparant proxies.

**Comment by yani** [comment] 2017-10-30 07:46
I think the problem is that there is no proxy loaded:

Try changing the following line on line 61 in [modules/ProxyChecker.php](https://github.com/yanikore/phpBrute/blob/master/modules/ProxyChecker.php):
`if ($this->curl = new CurlHandle($proxy, $useragent)) {`

To:
`if ($this->curl = new CurlHandle($data['proxy'], $useragent)) {`

In the latest version I added a custom cURL wrapper and because the wrapper was fully working, I changed most of the code that now uses it without double checking. I will fix the file when I get home.

**Comment by djoey123** [comment] 2017-10-30 13:49
Looks like it is working fine now.

It seems like it doesnt use mutli threading. think it is my failt :P

**Comment by yani** [comment] 2017-11-04 10:09
Fixed in 60e2eb4

**Closed as completed** 2017-11-04 10:10 UTC
